<div class="modal-body">
    <p style="text-align: center; padding-top: 30px;font-size: larger;color: black">协议</p>
    <p style="margin-left: 5%">Website Visitors</p>
    <div class="Privacy">Like most website operators, MeFon collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. MeFon’s purpose in collecting non-personally identifying information is to better understand how MeFon’s visitors use its website. From time to time, MeFon Ventures Inc. may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</div>

    <div class="Privacy">MeFon also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on MeFon.ca blogs/sites. MeFon only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below, except that commenter IP addresses and email addresses are visible and disclosed to the administrators of the blog/site where the comment was left.</div>
    <p style="margin-left: 5%">Gathering of Personally-Identifying Information</p>
    <div class="Privacy">Certain visitors to MeFon’s websites choose to interact with MeFon in ways that require MeFon to gather personally-identifying information. The amount and type of information that MeFon gathers depends on the nature of the interaction. For example, we ask visitors who sign up at MeFon.ca to provide a username and email address. Those who engage in transactions with MeFon are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, MeFon collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with MeFon Ventures Inc. MeFon Ventures Inc. does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</div>
    <p style="margin-left: 5%">Aggregated Statistics</p>
    <div class="Privacy">MeFon may collect statistics about the behavior of visitors to its websites. MeFon may display this information publicly or provide it to others. However, MeFon Ventures Inc. does not disclose personally-identifying information other than as described below.</div>
    <p style="margin-left: 5%">Protection of Certain Personally-Identifying Information</p>
    <div class="Privacy">MeFon discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on MeFon behalf or to provide services available at MeFon websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using MeFon’s websites, you consent to the transfer of such information to them. MeFon will not rent or sell potentially personally-identifying and personally-identifying information to anyone.</div>
    <div class="Privacy">Other than to its employees, contractors and affiliated organizations, as described above, MeFon discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when MeFon believes in good faith that disclosure is reasonably necessary to protect the property or rights of MeFon, third parties or the public at large. If you are a registered user of a MeFon website and have supplied your email address, MeFon may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with MeFon and our products. If you send us a request (for example via email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. MeFon takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</div>
    <p style="margin-left: 5%">Cookies</p>
    <div class="Privacy">A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. MeFon uses cookies to help MeFon identify and track visitors, their usage of MeFon website, and their website access preferences. MeFon visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using MeFon’s websites, with the drawback that certain features of MeFon’s websites may not function properly without the aid of cookies.</div>
    <p style="margin-left: 5%">Business Transfers</p>
    <div class="Privacy">If MeFon or substantially all of its assets, were acquired, or in the unlikely event that MeFon goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of MeFon Ventures Inc. may continue to use your personal information as set forth in this policy.</div>
    <p style="margin-left: 5%">Ads</p>
    <div class="Privacy">Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by MeFon and does not cover the use of cookies by any advertisers.</div>
    <p style="margin-left: 5%">Privacy Policy Changes</p>
    <div class="Privacy">Although most changes are likely to be minor, MeFon may change its Privacy Policy from time to time, and in MeFon Ventures Inc.’s sole discretion. MeFon encourages visitors to frequently check this page for any changes to its Privacy Policy. If you have a MeFon.ca account, you might also receive an alert informing you of these changes. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</div>
    <button class="close" style="background-color: #00CC00;width: 30%;border-radius: 5%;">Ok</button>
</div>